databases:
  - name: testrender
    databaseName: testrender
    user: testrender

services:
  - type: web
    name: testrender
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: testrender
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
